- id: forbid-pushing-wip
  description: Deny pushing WIP repo state
  entry: scripts/forbid-pushing-wip
  language: script
  name: forbid-pushing-wip
  stages: [push]
- id: forbid-committing-go-mod-replace
  description: Forbid commiting `replace` entries in go.mod files
  entry: scripts/forbid-go-mod-replace-commit
  language: script
  name: forbid-go-mod-replace-commit
  stages: [commit]
- id: tag-branch-commit
  description: Prefix commit message with current branch name
  entry: scripts/tag-branch-commit
  language: script
  name: tag-branch-commit
  stages: [prepare-commit-msg]
- id: hide-devenv-stgit
  description: Hide transient development environment files, using StGit
  entry: scripts/hide-devenv-stgit
  language: script
  name: hide-devenv-stgit
  stages: [commit]
- id: unhide-devenv
  description: Unhide transient development environment files
  entry: scripts/unhide-devenv
  language: script
  name: unhide-devenv
  stages: [post-commit]
- id: unhide-devenv-stgit
  description: Unhide transient development environment files, using StGit
  entry: scripts/unhide-devenv-stgit
  language: script
  name: unhide-devenv-stgit
  stages: [post-commit]
- id: nixfmt
  description: Formatting Nix sources
  entry: scripts/nixfmt
  files: "\\.nix$"
  language: script
  name: nixfmt
  stages: [commit]
# TODO: add preventing pushing FIXMEs
