- id: forbid-pushing-wip
  description: Deny pushing WIP repo state
  entry: scripts/forbid-pushing-wip
  language: script
  name: forbid-pushing-wip
  stages: [push]
- id: nixfmt
  description: Formatting Nix sources
  entry: scripts/nixfmt
  files: "\\.nix$"
  language: script
  name: nixfmt
  stages: [commit]
- id: tag-branch-commit
  description: Prefix commit message with current branch name
  entry: scripts/tag-branch-commit
  language: script
  name: tag-branch-commit
  stages: [prepare-commit-msg]
- id: unhide-devenv
  description: Unhide transient development environment files
  entry: scripts/unhide-devenv
  language: script
  name: unhide-devenv
  stages: [post-commit]
- id: go-mod-prohibit-replace
  description: Prohibit commiting `replace` entries in go.mod files
  entry: scripts/go-mod-prohibit-replace
  language: script
  name: go-mod-prohibit-replace
  stages: [commit]
