- id: forbid-pushing-wip
  name: forbid-pushing-wip
  description: Deny pushing WIP repo state
  entry: scripts/forbid-pushing-wip
  language: script
  stages: [push]
- id: nixfmt
  name: nixfmt
  description: Formatting Nix sources
  language: script
  entry: "scripts/nixfmt"
  files: "\\.nix$"
  stages: [commit]
- id: tag-branch-commit
  name: tag-branch-commit
  description: Prefix commit message with current branch name
  language: script
  entry: "scripts/tag-branch-commit"
  stages: [prepare-commit-msg]
