- id: forbid-pushing-wip
  name: forbid-pushing-wip
  description: Deny pushing WIP repo state
  entry: scripts/forbid-pushing-wip
  language: script
  stages: [push]
- id: nixfmt
  name: nixfmt
  description: Formatting Nix sources
  language: script
  entry: "scripts/nixfmt"
  files: "\\.nix$"
  stages: [commit]
