- id: forbid-pushing-wip
  description: Deny pushing WIP repo state
  entry: scripts/forbid-pushing-wip
  language: script
  name: forbid-pushing-wip
  stages: [push]
- id: forbid-pushing-devenv
  description: Deny pushing devenv upstream
  entry: scripts/forbid-pushing-devenv
  language: script
  name: forbid-pushing-devenv
  stages: [push]
- id: forbid-committing-go-mod-replace
  description: Forbid commiting `replace` entries in go.mod files
  entry: scripts/forbid-go-mod-replace-commit
  language: script
  name: forbid-go-mod-replace-commit
  stages: [commit]
- id: tag-branch-commit
  description: Prefix commit message with current branch name
  entry: scripts/tag-branch-commit
  language: script
  name: tag-branch-commit
  stages: [prepare-commit-msg]
- id: nixfmt
  description: Formatting Nix sources
  entry: scripts/nixfmt
  files: "\\.nix$"
  language: script
  name: nixfmt
  stages: [commit]
- id: nixpkgs-fmt
  description: Formatting Nix sources
  entry: scripts/nixpkgs-fmt
  files: "\\.nix$"
  language: script
  name: nixpkgs-fmt
  stages: [commit]
- id: Isort
  description: Ensure Python imports ordering with isort
  entry: scripts/isort
  files: "\\.py$"
  language: script
  name: isort
  stages: [commit]
# TODO: add preventing pushing FIXMEs
