#!/usr/bin/env bash

commit=$(git log --pretty=oneline | grep -e "\[wip\]" -e "\[WIP\]")
if [ ! -z "$commit" ]; then
    echo $commit
    echo >&2 "Found WIP commit(s), canceled pushing"
    exit 1
fi
