#!/usr/bin/env python
import sys
from subprocess import check_output

unpushed_commits = check_output(['git', 'log', '--pretty=oneline', '@{u}..']).decode().strip().split("\n")
wip_commits = []
for commit in unpushed_commits:
    if "wip" in commit or "WIP" in commit or commit.startswith("fixup"):
        wip_commits.append(commit)

if len(wip_commits):
    print("found work-in-progress commit(s), cannot push:\n{0}".format('\n'.join(wip_commits)))
    sys.exit(1)
