#!/usr/bin/env python
import sys, re
from subprocess import check_output

commit_msg_filepath = sys.argv[1]

branch = check_output(["git", "symbolic-ref", "--short", "HEAD"]).strip()
print(f"branch: {branch}")
if branch == 'master':
    print("not tainting master branch")
    sys.exit(1)

prefix = f"{branch.decode()}: "
with open(commit_msg_filepath, "r+") as fh:
    commit_msg = fh.read()
    if not commit_msg.startswith(prefix):
        fh.seek(0, 0)
        fh.write(f"{prefix}{commit_msg}")
